
{"asctime": "2025-04-21 13:17:31,942", "levelname": "ERROR", "name": "bot", "message": "Handled exception in User", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\modules\\users\\User.py\", line 93, in set_photo\n    photo = message.photo[-1]\n            ~~~~~~~~~~~~~^^^^\nTypeError: 'NoneType' object is not subscriptable", "exception": "User didnt send photo", "user_id": 1045393239, "user_name": "Mandarinchik2315"}
{"asctime": "2025-04-21 13:17:34,939", "levelname": "ERROR", "name": "bot", "message": "Handled exception in User", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Dmitriy\\Desktop\\Bless-bot\\modules\\users\\User.py\", line 93, in set_photo\n    photo = message.photo[-1]\n            ~~~~~~~~~~~~~^^^^\nTypeError: 'NoneType' object is not subscriptable", "exception": "User didnt send photo", "user_id": 1045393239, "user_name": "Mandarinchik2315"}
